// src/js/constants/action-types.js

const ADD_ARTICLE = "ADD_ARTICLE";
const API_CALL_FINISHED = "API_CALL_FINISHED";
const TOGGLE_JOB_DETAILS = "TOGGLE_JOB_DETAILS"
const CLEAR_STATE_ACTION = "CLEAR_STATE_ACTION";
const DISALLOW_OPEN_DIALOG = "DISALLOW_OPEN_DIALOG"; 
const ALLOW_OPEN_DIALOG = "ALLOW_OPEN_DIALOG"; 

export {
  ADD_ARTICLE,
  API_CALL_FINISHED,
  TOGGLE_JOB_DETAILS,
  CLEAR_STATE_ACTION,
  DISALLOW_OPEN_DIALOG,
  ALLOW_OPEN_DIALOG
}