
const API_CALLER_CONSTANTS = {
  OPTIONS_FOR_UTILITIES_WITH_WHICH_TO_CALL_API: {
    AXIOS: "AXIOS",
    FETCH: "FETCH"
  },
  REFERER: {
  USE_DEFAULT: "USE_DEFAULT",
  DO_NOT_SEND_HEADER: "DO_NOT_SEND_HEADER"

  }
}

export default API_CALLER_CONSTANTS