const SYNC_VIEW = "SYNC_VIEW"
const STITCH_VIEW = "STITCH_VIEW"
const MPEG_CONVERSION_VIEW = "MPEG_CONVERSION_VIEW"
const LOCAL_DOWNLOAD_VIEW = "LOCAL_DOWNLOAD_VIEW"

export {
  SYNC_VIEW,
  STITCH_VIEW,
  MPEG_CONVERSION_VIEW,
  LOCAL_DOWNLOAD_VIEW
}